name: automerge

on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.7.1
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
